# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("plugin.proto", :syntax => :proto3) do
    add_message "io.pact.plugin.InitPluginRequest" do
    end
    add_message "io.pact.plugin.InitPluginResponse" do
    end
  end
end

module Io
  module Pact
    module Plugin
      InitPluginRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.pact.plugin.InitPluginRequest").msgclass
      InitPluginResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.pact.plugin.InitPluginResponse").msgclass
    end
  end
end
